# config.yaml
# === Subject info ===
subinfo_fields:
  - name: subject_id
    type: int
    constraints:
      min: 101
      max: 999
      digits: 3


  - name: subname    
    type: string

  - name: age 
    type: int
    constraints:
      min: 5
      max: 60

  - name: gender
    type: choice
    choices: [Male, Female]

subinfo_mapping:
    subject_id: "被试号"
    subname: "被试姓名(拼音)"
    age: "年龄"
    gender: "性别"
    Male: "男"
    Female: "女"
    registration_failed: "注册失败。"
    registration_successful: "注册成功！"
    invalid_input: "字段 {field} 输入无效"


# === Window settings ===
window:
  size: [2560, 1600]
  units: deg
  screen: 1
  bg_color: black
  fullscreen: True
  monitor_width_cm: 34.5
  monitor_distance_cm: 60

# === Task-level settings ===
task:
  task_name: "eeg_emodot"
  total_blocks: 3
  total_trials: 240
  trial_per_block: 80
  conditions:   
    - PN_F_L # positive, neutral, female, left
    - PN_F_R # positive, neutral, female, right
    - NP_F_L # neutral, positive, female, left
    - NP_F_R # neutral, positive, female, right
    - SN_F_L # negative, neutral, female, left
    - SN_F_R # negative , neutral, female, right
    - NS_F_L # neutral, negative, female, left
    - NS_F_R # neutral, negative, female, right
    - PN_M_L 
    - PN_M_R 
    - NP_M_L
    - NP_M_R
    - SN_M_L
    - SN_M_R
    - NS_M_L
    - NS_M_R
    - NN_F_L
    - NN_F_R
    - NN_M_L
    - NN_M_R
  key_list: [f, j]
  left_key: f
  right_key: j
  seed_mode: "same_across_sub"


# === Stimuli  ===
stimuli:
  fixation:
    type: text
    text: "+"
    color: white
  
  left_stim:
    type: image
    pos: [-4.5, 0]
    size: [4.5, 5]
    units: deg
  
  right_stim:
    type: image
    pos: [4.5, 0]
    size: [4.5, 5]
    units: deg
  
  left_target:
    type: circle
    radius: 1
    pos: [-4, 0]
    color: white
  
  right_target:
    type: circle
    radius: 1
    pos: [4, 0]
    color: white

  
  block_break:
    type: text
    text: |
      第 {block_num} / {total_blocks} 部分完成
      击中率：{accuracy:.2f}

      请在充分休息后按下空格键
      进入下一个部分
    color: white
    height: 0.78



  instruction_text:
    type: textbox
    text: |
      【情绪点探测任务说明】

      在本任务中，您将首先看到一个注视点
      接着会出现一对面孔图片
      短暂呈现后，屏幕上会出现一个点

      您的任务是尽快按键，指示点出现的位置：
        - 如果点在左侧，请用左手食指按【f】
        - 如果点在右侧，请用右手食指按【j】

      请尽可能快速且准确地作出反应

      准备好后，请按【空格键】开始任务。
    color: white
    font: SimHei
    alignment: center
    letterHeight: 0.78
    units: deg
    size: [20, 5]

  good_bye:
    type: textbox
    text: |
      【任务结束】

      感谢您的参与！
      请按【空格键】退出任务

    color: white
    font: SimHei
    alignment: center
    letterHeight: 0.78
    units: deg
    size: [20, 5]


# === Timing & Adaptivity ===
timing:
  fixation_duration: 0.3
  cue_duration: 0.5
  interval_duration: [0.4, 0.6]
  target_duration: 1.2


triggers:
  exp_onset: 98
  exp_end: 99

  block_onset: 198
  block_end: 199

  key_press: 68
  no_reponse: 69

  PN_F_L_fixation_onset: 11
  PN_F_L_cue_onset: 12
  PN_F_L_target_onset: 13
  PN_F_L_key_press: 14
  PN_F_L_no_response: 15

  PN_F_R_fixation_onset: 21
  PN_F_R_cue_onset: 22
  PN_F_R_target_onset: 23
  PN_F_R_key_press: 24
  PN_F_R_no_response: 25

  NP_F_L_fixation_onset: 31
  NP_F_L_cue_onset: 32
  NP_F_L_target_onset: 33
  NP_F_L_key_press: 34
  NP_F_L_no_response: 35

  NP_F_R_fixation_onset: 41
  NP_F_R_cue_onset: 42
  NP_F_R_target_onset: 43
  NP_F_R_key_press: 44
  NP_F_R_no_response: 45

  SN_F_L_fixation_onset: 51
  SN_F_L_cue_onset: 52
  SN_F_L_target_onset: 53
  SN_F_L_key_press: 54
  SN_F_L_no_response: 55

  SN_F_R_fixation_onset: 61
  SN_F_R_cue_onset: 62
  SN_F_R_target_onset: 63
  SN_F_R_key_press: 64
  SN_F_R_no_response: 65

  NS_F_L_fixation_onset: 71
  NS_F_L_cue_onset: 72
  NS_F_L_target_onset: 73
  NS_F_L_key_press: 74
  NS_F_L_no_response: 75

  NS_F_R_fixation_onset: 81
  NS_F_R_cue_onset: 82
  NS_F_R_target_onset: 83
  NS_F_R_key_press: 84
  NS_F_R_no_response: 85

  PN_M_L_fixation_onset: 91
  PN_M_L_cue_onset: 92
  PN_M_L_target_onset: 93
  PN_M_L_key_press: 94
  PN_M_L_no_response: 95

  PN_M_R_fixation_onset: 101
  PN_M_R_cue_onset: 102
  PN_M_R_target_onset: 103
  PN_M_R_key_press: 104
  PN_M_R_no_response: 105

  NP_M_L_fixation_onset: 111
  NP_M_L_cue_onset: 112
  NP_M_L_target_onset: 113
  NP_M_L_key_press: 114
  NP_M_L_no_response: 115

  NP_M_R_fixation_onset: 121
  NP_M_R_cue_onset: 122
  NP_M_R_target_onset: 123
  NP_M_R_key_press: 124
  NP_M_R_no_response: 125

  SN_M_L_fixation_onset: 131
  SN_M_L_cue_onset: 132
  SN_M_L_target_onset: 133
  SN_M_L_key_press: 134
  SN_M_L_no_response: 135

  SN_M_R_fixation_onset: 141
  SN_M_R_cue_onset: 142
  SN_M_R_target_onset: 143
  SN_M_R_key_press: 144
  SN_M_R_no_response: 145

  NS_M_L_fixation_onset: 151
  NS_M_L_cue_onset: 152
  NS_M_L_target_onset: 153
  NS_M_L_key_press: 154
  NS_M_L_no_response: 155

  NS_M_R_fixation_onset: 161
  NS_M_R_cue_onset: 162
  NS_M_R_target_onset: 163
  NS_M_R_key_press: 164
  NS_M_R_no_response: 165

  NN_F_L_fixation_onset: 171
  NN_F_L_cue_onset: 172
  NN_F_L_target_onset: 173
  NN_F_L_key_press: 174
  NN_F_L_no_response: 175

  NN_F_R_fixation_onset: 181
  NN_F_R_cue_onset: 182
  NN_F_R_target_onset: 183
  NN_F_R_key_press: 184
  NN_F_R_no_response: 185

  NN_M_L_fixation_onset: 191
  NN_M_L_cue_onset: 192
  NN_M_L_target_onset: 193
  NN_M_L_key_press: 194
  NN_M_L_no_response: 195

  NN_M_R_fixation_onset: 201
  NN_M_R_cue_onset: 202
  NN_M_R_target_onset: 203
  NN_M_R_key_press: 204
  NN_M_R_no_response: 205
  

